FrontendBundle\Entity\Test:
    type: entity
    table: test
    id:
        id:
            type: string
            nullable: false
            length: 10
            options:
                fixed: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        test:
            type: string
            nullable: true
            length: 10
            options:
                fixed: true
    lifecycleCallbacks: {  }
