#FRONTEND
frontend_homepage:
    path:     /
    defaults: { _controller: FrontendBundle:Accueil:index }
frontend_test:
    path:     /test
    defaults: { _controller: FrontendBundle:Accueil:index }
frontend_erreur:
    path:     /erreur
    defaults: { _controller: FrontendBundle:Accueil:erreur }
#FRONTEND

#CONNEXION
connexion_formulaire:
    path:     /connexion
    defaults: { _controller: FrontendBundle:Connexion:formulaire }
#CONNEXION

#UTILISATEUR
utilisateur_liste:
    path:     /utilisateur/liste
    defaults: { _controller: FrontendBundle:Utilisateur:liste }
#UTILISATEUR